# bundle_id = "domain.id"
# path is the relative path to the workflow in the project root
---
path: workflow
domain: com.liftedstudios
id: github
createdby: Lee Dohm
webaddress: https://github.com/lee-dohm/github.workflow
