#!/usr/bin/env ruby -w

require 'fileutils'

include FileUtils::Verbose

dirs = ['~',
        'Cloud Drive',
        'Configuration',
        'Alfred',
        'Alfred.alfredpreferences',
        'workflows',
        'user.workflow.94ACFE38-521F-4E46-8690-1F0D700BA418']
INSTALL_DIR = File.expand_path(File.join(*dirs))

cd(INSTALL_DIR) do
  rm_rf '*'
end

cp_r '.', INSTALL_DIR
